---
title: "Screen Pixel Ruler `r params$version`"
author: "Stewart Cossey"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: cossey/screenpixelruler2
description: "Help documentation for Screen Pixel Ruler."
params:
  version: "MASTER"
---

# Overview

Screen Pixel Ruler is an on-screen tool that helps you measure elements on web pages, documents, or software that don't have a built-in ruler.
It's built on .NET Core 3.1 and inspired by MioPlanet PixelRuler.
The software works on Windows 7 and later.

Free and open source, it's licensed under the [BSD 3-Clause License](https://opensource.org/licenses/BSD-3-Clause).

## Features

* Global hotkeys to trigger functionality when other software is in focus.
* Rotatable vertical or horizontal ruler. `Ctrl + Shift + Alt + R`
* Customizable ruler themes.
* Freezable position. `Ctrl + Shift + Alt + F`
* Guideline system that can lock the mouse cursor horizontally or vertically
* Position 0 of the ruler to the current cursor location. `Ctrl + Shift + Alt + S`

> A list of all shorcuts can be found [here](\#keyboard).

## Installation

Screen Pixel Ruler can be installed from either the [Installer](https://github.com/Cossey/ScreenPixelRuler2/releases) or via [Chocolatey Package Management](https://chocolatey.org) by running the command `choco install screenpixelruler`.
Both the installer and package will install the .NET Core 3.1 runtime if it is not present.

## Providing feedback

You can report bugs or request features by opening an issue on the [GitHub repository](https://github.com/Cossey/ScreenPixelRuler2).
Any contributions are also welcome and can be done by creating a pull request.