name: Help

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Render
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1
      - name: Setup Tinytex
        uses: r-lib/actions/setup-tinytex@v1
      - name: Setup rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Build HTML
        run: |
          cd Help
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
      - name: Build ePub
        run: |
          cd Help
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"
      - name: Build PDF
        run: |
          cd Help
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Help
          path: Help/_book/
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: Help
          path: Help/_book/
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: Help/_book/
          target-folder: help/latest