name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: .NET
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Code
      run: msbuild -r -p:Configuration=Release

    - name: Test Code
      run: dotnet test --no-restore --verbosity normal

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: compiled-files
        path: ScreenPixelRuler2/bin/Release/**/

    - name: Build Installer
      run: iscc /F"installer.exe" Deployment\Installer\Installer.iss
  
    - name: Test Installer
      run: |
        cd Deployment\Installer\Output 
        .\installer.exe /SP- /VERYSILENT /SUPPRESSMSGBOXES /LOG=".\install.log"
  
    - name: Upload Install log
      uses: actions/upload-artifact@v2
      with:
        name: install-log
        path: Deployment\Installer\Output\install.log