name: Publish

on:
  milestone:
    types: [closed]

jobs:
  net:
    name: Compile Software
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2

    - name: Compile code
      run: msbuild -r -p:Version=${{ github.event.milestone.title }} -p:Configuration=Release

    - name: Remove unrequired files
      run: Remove-Item ScreenPixelRuler2/bin/Release/net8.0-windows7.0/* -include *.pdb
      shell: pwsh

    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-files
        path: ScreenPixelRuler2/bin/Release/net8.0-windows7.0

    - name: Compile installer
      run: iscc Deployment\Installer\Installer.iss

    - name: Upload deployment artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deployment-files
        path: |
          Deployment/Installer/Output/${{ steps.install_name.outputs.filename }}
          Deployment/Choco
          Resources
          LICENSE.md
          .github/release-notes.yml

  release-notes:
    name: Create Release Notes
    runs-on: ubuntu-latest
    needs: net

    steps:
    - name: Create release notes
      uses: docker://decathlon/release-notes-generator-action:3.1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes

    - name: Upload release note artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-notes
        path: temp_release_notes/changelog.md
        if-no-files-found: error

  net-deploy:
    name: Publish Github Release
    runs-on: ubuntu-latest
    needs: release-notes

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.milestone.title }}
        release_name: Release ${{ github.event.milestone.title }}
        body_path: release-notes/changelog.md
        draft: false
        prerelease: false
        make_latest: true
        fail_on_unmatched_files: true
        files: |
          deployment-files/Deployment/Installer/Output/ScreenPixelRuler-${{ github.event.milestone.title }}.exe

  net-choco:
    name: Publish Chocolatey Release
    runs-on: windows-latest
    needs: release-notes

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Setup package details
      run: |
        $content = Get-Content -Path 'artifacts/deployment-files/Deployment/Choco/screenpixelruler.nuspec'
        $content = $content -replace '%version%', '${{ github.event.milestone.title }}'
        $releasenotes = (Get-Content -Raw -Path 'artifacts/release-notes/changelog.md') -replace '\n',"`r`n" 
        $content = $content -replace '%releasenotes%', $releasenotes
        $content | Set-Content -Path 'artifacts/deployment-files/Deployment/Choco/screenpixelruler.nuspec'
      shell: pwsh

    - name: Copy software to package
      run: |
        Copy-Item -Path 'artifacts/compiled-files/*' -Destination 'artifacts/deployment-files/Deployment/Choco/tools'
        Copy-Item -Path 'artifacts/deployment-files/Resources/*.thm' -Destination 'artifacts/deployment-files/Deployment/Choco/tools'
        Copy-Item -Path 'artifacts/deployment-files/LICENSE.md' -Destination 'artifacts/deployment-files/Deployment/Choco/tools'
      shell: pwsh
    
    - name: Create package
      run: choco pack
      working-directory: artifacts/deployment-files/Deployment/Choco

    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: package-file
        path: artifacts/deployment-files/Deployment/Choco/*
        if-no-files-found: error

    - name: Upload package to chocolatey repository
      run: choco push --source https://push.chocolatey.org/ --api-key=${{ secrets.CHOCO_API_KEY }}
      working-directory: artifacts/deployment-files/Deployment/Choco
  
  help:
    name: Build Help
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup Tinytex
        uses: r-lib/actions/setup-tinytex@v2
      - name: Setup rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Build HTML
        run: |
          cd Help
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook', params = list(version = '${{ github.event.milestone.title }}'))"
      - name: Build ePub
        run: |
          cd Help
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book', params = list(version = '${{ github.event.milestone.title }}'))"
      - name: Build PDF
        run: |
          cd Help
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book', params = list(version = '${{ github.event.milestone.title }}'))"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Help
          path: Help/_book/

  help-deploy:
    name: Deploy Help
    runs-on: ubuntu-latest
    needs: help
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Help
          path: Help/_book/
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: Help/_book/
          target-folder: help/${{ github.event.milestone.title }}
      - run: |
          echo "::notice title=Bookdown Deployment::Accessible at https://cossey.github.io/ScreenPixelRuler2/help/${{ github.event.milestone.title }}/"
